ShishirPatil/gorilla

README.md
inference/README.md

In this PR we release the weights for Gorilla 0-shot model for Torch Hub and Tensorflow Hub APIs 🎉
It chooses from 626 (exhaustive) TensorFlow v2 APIs, and 94 (exhaustive) Torch Hub  in a 0-shot fashion (without any retrieval). In the spirit of being open, we do not filter, nor carry out any post processing either to the prompt nor response 🎁 We would like to remind the community that neither of `gorilla-7b-hf-v0`, `gorilla-7b-tf-v0`, nor `gorilla-7b-th-v0` have any generic chat capability. We do have a model with all the 1600+ APIs which also has generic chat capability, which we release slowly to accommodate server demand.
You can play around with Gorilla either through our hosted colab (OpenAI Chat completion API compliant) or you can download and run it locally.
Thank you for all the …

Releasing Torch and TF weights 🚀 

---

inference/README.md
inference/serve/gorilla_cli.py

In gorilla_cli.py the argument must be `model-path` and not `model`

Fix: gorilla_cli.py `model` to `model-path`

---

README.md
data/README.md
eval/README.md
eval/eval-scripts/ast_eval_hf.py
eval/eval-scripts/ast_eval_tf.py
eval/eval-scripts/ast_eval_th.py
eval/get_llm_responses.py
eval/get_llm_responses_retriever.py
eval/retrievers/__init__.py
eval/retrievers/bm25.py
eval/retrievers/build_json_index.py
eval/retrievers/gpt.py
eval/retrievers/schema.py
inference/gorilla_eval.py
requirements.txt

Gorilla introduces Retriever Aware Training (RAT). Here we include the code for retrievers. Note that while you can use  {prompt + retrieved API} with the 0-shot trained Gorilla LLMs for inference, for optimal performance, we recommend you use {prompt + retrieved API} with RAT trained Gorilla LLM for inference. 
More precisely, BM25 refers to `BM25Okapi` and GPT refers to `text-embedding-ada-002-v2`
Directly relevant to #58 and might be useful for #32 
+ Removing unused legacy code from `ast_eval_*.py`
+ Updating Apache 2.0 license for all of Gorilla code

Adding BM25 and GPT retrievers

---

eval/eval-scripts/ast_eval_hf.py
eval/get_llm_responses.py

Add Weights & Biases logging to:
- log the llm responses in a file and in a W&B Table to explore
- Keep track of progress of llm responses progress (helpful during long llm response queries)
- log the ast evaluation accuracy of the logged responses

Adds wandb to eval files

---

eval/eval-scripts/ast_eval_hf.py
eval/get_llm_responses.py

- Fix `use_wandb` to be `args.use_wandb`
- deletes existing responses file if one is found (otherwise data is appended)
- Fix W&B artifacts logging
- Only append to table if line from jsonl is not none
- Enforce artifacts naming conventions (will error if `:` are present)

Fix use_wandb in ast eval, responses file deletion, wandb artifacts renaming

---

README.md
openfunctions/README.md
openfunctions/gorilla_openfunctions_test.json

🔥 Excited to release Gorilla OpenFunctions! 
+ Drop-in alternative
+ Apache 2.0 models
+ With parallel function calling as well
Read more in our [Release blog](https://gorilla.cs.berkeley.edu/blogs/4_open_functions.html)

Gorilla OpenFunctions

---

openfunctions/README.md

Added example on how to run the LLM locally using Hugging Face 🤗 Transformers

Example on running it locally with Hugging Face 🤗 Transformers

---

data/apizoo/Gmail_API.json

Added the Gmail API (Python) to API Zoo. This includes all of the methods available to users except for the methods that require the client-side encryption (CSE) configuration. This is not accessible by the regular API user.

Added Gmail api to api zoo

---

data/apizoo/felixzhu1.json

Added a subset of the Google Maps API with the [python client](https://github.com/googlemaps/google-maps-services-python) to the API zoo. This includes the core Maps APIs:
- Address Validation API
- Directions API
- Distance Matrix API
- Elevation API
- Geocoding API
- Geolocation API
- Time Zone API
- Roads API
- Places API
- Maps Static API
[Here](https://developers.google.com/maps/apis-by-platform) is the Google Maps API breakdown and documentation, and [here](https://googlemaps.github.io/google-maps-services-python/docs/index.html) is the documentation I referenced for the `googlemaps` python library. Note that using the Google Maps API requires [setting up a Google Cloud project](https://developers.google.com/maps/get-started) and generating an API key.

Add Google Maps API (python client)

---

data/apizoo/aryanvichare.json

The "OpenWeatherMap API" now supports fetching current and forecast weather data as well as historical weather data with the latest update. This API enables users to retrieve minute-by-minute, hourly, and daily forecasts, along with government weather alerts.
For current and forecast weather data, utilize the openweathermap.one_call() function by providing latitude, longitude, exclusion parameters, and your unique API key. The API version 3.0 offers options for units of measurement: standard, metric, and imperial.
To access historical weather data for a specific timestamp, the openweathermap.time_machine() function is available. Specify the latitude, longitude, timestamp (Unix time in UTC), and API key to retrieve historical weather information.

Add support for the OpenWeatherMap API

---

data/apizoo/danielgeorge.json

Added in Stripe API into gorilla zoo.

Stripe Additions

---

index.js
leaderboard.html

Update leaderboard data and wagon wheel data to reflect new models and the updated rest API eval result.
Change leaderboard to include `mistral-large-2402`, `gemini-1.0-pro`, and `gemma-7b`.
Change leaderboard evals to be consistent with #234

Leaderboard update: mistral-large-2402, gemini-1.0-pro and gemma 7-b; Update REST eval. 

---

leaderboard.html

Update the `overall` accuracy columns for the leaderboard, as the new rest API evaluation result changed those values. 
Note, this change is not reflected in the previous pr #237 .

Patch: Updating the overall column of the leaderboard numbers to reflect #237

---

index.js
leaderboard.html

This PR renamed the following models to be more precise.
1. GPT-3.5-Turbo to GPT-3.5-Turbo-0125
2. claude-instant to claude-instant-1.2
3. mistral-tiny to mistral-tiny-2312
4. mistral-small to mistral-small-2312
5. mistral-medium to mistral-medium-2312
6. mistral-large-2402 to mistral-large-2402

Rename models on leaderboard. 

---

data/apizoo/GoogleFormsAPI.json

Added the methods for Google Forms API.

Added Google Forms API

---

data.csv
index.js

This PR updates the data.csv file, which turns out to be outdated. This does not change the values of the leaderboard.
In order to support an inquiry from Gradio that needs a human-readable format of the leaderboard data, we have made some changes to the data.csv file, especially in the order of columns and their naming (and we added a few columns as well). Thus, the logic for rendering the leaderboard from the data.csv also needs to be changed. On the website, the logic has been updated. However the data.csv itself is not updated, thus causing some rendering issues.

Rendering Bug Fix for Leaderboard

---

openfunctions/utils/java_parser.py
openfunctions/utils/js_parser.py

**Context**: Parser is used to convert model response str -> OpenAI compatible `function_call`
- Corrected edge cases with `new` keyword
- Corrected `[Class.]method` optionally include Class in method. 
- Add recursive logic in `traverse_node` java parser, to special handle strings
- Corrected initialization with `ArrayList`, `Array` keywords formatting.
- Additional comments, example usage and expected outputs included.
**Example:** `PmsProductServiceImpl.updateNewStatus(ids=new ArrayList<Long>(Arrays.asList(101L, 202L, 303L)), newStatus=2)` -> `{'function': {'name': 'PmsProductServiceImpl.updateNewStatus', 'parameters': {'ids': 'new ArrayList<Long>(Arrays.asList(101L, 202L, 303L))', 'newStatus': '2'}}}`

[Fix] java, javascript parsers in openfunctions-v2

---

berkeley-function-call-leaderboard/README.md

- Corrected a legacy path to be consistent in berkeley-function-call-leaderboard folder README instruction.

Correction in BFCL README instruction, fixed path in instructions

---

berkeley-function-call-leaderboard/model_handler/constant.py
berkeley-function-call-leaderboard/openfunctions_evaluation.py

This pull request addresses several minor issues found in the evaluation script and system prompts.
I also found some errors in one of the dataset as outlined below.
1. Fixed a typo in the system prompt for chat models to ensure clarity in instructions provided to the model.
2. Evaluation Script Updates (`openfunctions_evaluation.py`):
- Modified function parameters in `build_handler` to directly pass `temperature`, `top_p`, and `max_tokens` which enhances the readability and maintainability of the code.
- Corrected the conditional checks and variable assignments to accurately reflect the intended logic for handling different test categories.
Two errors were identified in the dataset file `gorilla_openfunctions_v1_test_parallel_multiple_function.json`:
1. **Line 58**: We should change …

Fix Typos in Evaluation Script and System Prompt. Identify Errors in a Dataset

---

.gitignore
goex/README.md
goex/docker/misc/images.json
goex/exec_engine/db_manager.py
goex/exec_engine/fs_manager.py
goex/main.py

Addressed bugs, and thoroughly tested with both Option 1 and 2, start to finish for all the examples, for all DB types.
- README `fspath` -> `fs_path`
- README added git lfs installation instructions, Press ctrl-d to exit out of the shell after sqlite3 creation
- DB Prompt formatting
- SQLite bug when executing multiple SQL statements at once, now it actually works
- Missing images.json -> Added
- FS too many git initializations -> only initializes once per execute
- FS initial commit now adds all the directory content
- Missing `.env` from `.gitignore` -> Added

FS/DB Bug Fixes Post-Migration

---

raft/raft.py

Change `p` which dictates the fraction of dataset with golden documents in them (vs) no golden documents. 
So, p = 0.8 means, for 80% of the train data set, `A* = Q + D* + D1 .. Dn` and for 20% of the train data set `A* = Q + D1 .. Dn` where `D*` are/is the golden document with the answer `A*`.
Close #325

Update raft.py with default `p` to match paper

---

goex/README.md

Existence of Docker + the need for it to be running locally is required in Goex, however not mentioned in the set up portion of README. Added it as part of this PR

Added Docker to README

---

berkeley-function-call-leaderboard/model_handler/constant.py

Hermes-2-Pro-Mistral-7B is the newly added OS model handler, the function definition is OpenAI compatible, so the API call like request.get will be modified to request_get in prompt. We should add this to UNDERSCORE_TO_DOT list to do the correct conversion of the label as well otherwise it will lead to very low scores which didn't match what has shown on leaderboard.
After adding the model, the score improves significantly:
| Overall ACC | Summary AST | Simple AST | Python AST | Multiple | Parallel | Parallel Multiple | Relevance |
|-------------|-------------|------------|------------|----------|----------|------------------|-----------|
|     0.55    |     0.47    |    0.33    |  0.33     |   0.345  |       0.69       |    0.52   | 1.0 |

[Bug fix] Add Hermes-2-Pro-Mistral-7B model to UNDERSCORE_TO_DOT to parse API properly 

---

berkeley-function-call-leaderboard/README.md
berkeley-function-call-leaderboard/apply_function_credential_config.py
berkeley-function-call-leaderboard/eval_checker/eval_runner_helper.py
berkeley-function-call-leaderboard/model_handler/claude_fc_handler.py
berkeley-function-call-leaderboard/model_handler/claude_prompt_handler.py
berkeley-function-call-leaderboard/model_handler/constant.py
berkeley-function-call-leaderboard/model_handler/handler_map.py
berkeley-function-call-leaderboard/model_handler/model_style.py
berkeley-function-call-leaderboard/model_handler/utils.py
berkeley-function-call-leaderboard/openfunctions_evaluation.py

This PR is for BFCL April 16th Release:
1. Switch to using Anthropic's new Tool Use Beta `tools-2024-04-04` when generating Claude 3 FC model data. 
2. `gpt-4-Turbo-2024-04-09` and `gpt-4-Turbo-2024-04-09-FC` are also added to the leaderboard.
This PR **DOES** change the leaderboard score. We will update the leaderboard shortly, in a different PR #365 
PS, this version does require the latest `anthropic` library, so make sure you update yours.
---------
Co-authored-by: Fanjia Yan <fanjiayan@berkeley.edu>
Co-authored-by: Charlie Cheng-Jie Ji <charliechengjieji@berkeley.edu>

BFCL April 16th Release

---

berkeley-function-call-leaderboard/eval_checker/eval_runner_helper.py

When you do API validation, we don't know which APIs fail. So I print out the APIs that fail so you know what is not working.

Log error messages from API validation

---

berkeley-function-call-leaderboard/README.md
berkeley-function-call-leaderboard/eval_checker/eval_runner_helper.py
berkeley-function-call-leaderboard/model_handler/arctic_handler.py
berkeley-function-call-leaderboard/model_handler/handler_map.py
berkeley-function-call-leaderboard/model_handler/nvidia_handler.py
berkeley-function-call-leaderboard/openfunctions_evaluation.py

In this PR, we have added `snowflake/arctic` to leaderboard:
- The inference was done through [Nvidia API catalog](https://build.nvidia.com/explore/discover#arctic) endpoint. Latencies are recorded and the cost is marked as "N/A" as the inference consumed Nvidia credits which were provided free upon registration.
- The leaderboard website will be updated shortly to reflect these new entries, in a different PR.
Notes on Nvidia API catalog: We didn't have enough compute resources to host full precision Arctic inference locally and therefore looked for third-party hosting. Out of Snowflake Cortex, Together.ai, and Nvidia API catalog, we decided to use Nvidia's service as it does not have context length limit and has detailed documentation of Python usage.

BFCL April 28th Release (New Model: snowflake/arctic)

---

berkeley-function-call-leaderboard/data/possible_answer/gorilla_openfunctions_v1_test_simple.json

I’m redoing the leaderboard results and scores for some models in the `simple` test category. I’ve noticed the model is marked down for answers that seem correct to me. Here are my suggestions for the corrections.
This PR DOES change the leaderboard scores, which will be updated later.

Small corrections to possible_answers for simple test category

---

blogs/5_how_to_gorilla.html

There has been a refactoring of the LangChain codebase earlier this year. I've updated the LangChain integration example to reflect this.
On running the example, this is the output -
```
<<<domain>>>: Natural Language Processing Translation
<<<api_call>>>: translation = pipeline('translation_en_to_zh', model='Helsinki-NLP/opus-mt-en-zh')
<<<api_provider>>>: Hugging Face Transformers
<<<explanation>>>: 1. Import the pipeline function from the transformers library provided by Hugging Face.
2. Create a translation pipeline using the 'Helsinki-NLP/opus-mt-en-zh' model, which is specifically designed for translating English text to Chinese.
3. Provide the input text to the translation pipeline and get the translated Chinese text.
<<<code>>>:
from transformers import pipeline
def load_model(): …
```

Update to LangChain integration example

---

.gitignore
raft/README.md
raft/format.py
raft/raft.py

Adds support to convert the dataset to formats expected to fine tune `completion` and `chat` models as specified there:
https://platform.openai.com/docs/guides/fine-tuning/preparing-your-dataset
`chat` format:
```
{"messages": [{"role": "system", "content": "Marv is a factual chatbot that is also sarcastic."}, {"role": "user", "content": "What's the capital of France?"}, {"role": "assistant", "content": "Paris, as if everyone doesn't know that already."}]}
{"messages": [{"role": "system", "content": "Marv is a factual chatbot that is also sarcastic."}, {"role": "user", "content": "Who wrote 'Romeo and Juliet'?"}, {"role": "assistant", "content": "Oh, just some guy named William Shakespeare. Ever heard of him?"}]}
{"messages": [{"role": "system", "content": "Marv is a factual chatbot that …
```

RAFT Support for chat and completion model formats

---

raft/raft.py

Added line `You MUST begin your final answer with the tag "<ANSWER>:".` in `encode_question_gen`'s prompt to ensure the `<ANSWER>:` tag is included in the label.

[RAFT] Edit encode prompt to include `<ANSWER>:` tag in label

---

berkeley-function-call-leaderboard/README.md
berkeley-function-call-leaderboard/eval_checker/eval_runner_helper.py
berkeley-function-call-leaderboard/model_handler/gemini_handler.py

Build on the work of @vandyxiaowei  #406, this PR is a bug fix for the generation pipeline for Gemini models ([Gemini-1.5-Pro (FC)](https://deepmind.google/technologies/gemini/#introduction) and [Gemini-1.0-Pro (FC)](https://deepmind.google/technologies/gemini/#introduction)) to make it more robust. The Gemini model output `result["candidates"][0]` does not always have the key `"content"`, which would cause the current generation pipeline to error out. 
This PR **DOES NOT** change the leaderboard score.

[BFCL] Patch Gemini Handler 

---

berkeley-function-call-leaderboard/requirements.txt

Following the instructions in the `BFCL` README and running the `eval_data_compilation.py` script results in this error:
```
AttributeError: type object 'tree_sitter.Language' has no attribute 'build_library'
```
because the `build_library` method was removed in a [recent release](https://github.com/tree-sitter/py-tree-sitter/releases/tag/v0.22.0) of py-tree-sitter. This PR updates the `requirements.txt` file so that the instructions in the README will work for anyone following them now.

[BFCL] update tree_sitter version in requirements.txt

---

berkeley-function-call-leaderboard/README.md

The code examples in the README use both triple backticks and indentation, which is not necessary and makes the code examples appear excessively indented. This is also annoying if you use the bash `HISTCONTROL=ignorespace` option, which causes commands prefaced with a space to not appear in history.
This PR removes the extra indentation.

Fix indentation in leaderboard README

---

berkeley-function-call-leaderboard/model_handler/claude_fc_handler.py

Anthropic just moved their tool use from beta to main so we have to change the import `from anthropic.types.beta.tools import ToolUseBlock` to `from anthropic.types import ToolUseBlock`. You cannot run the eval without this change as things break.
Also, my IDE automatically sorted the imported packages and removed some extra spaces -- this explains all the other changes.

Fix breaking changes due to updated Anthropic SDK

---

berkeley-function-call-leaderboard/README.md
berkeley-function-call-leaderboard/eval_checker/checker.py

This PR makes the BFCL evaluation pipeline more robust to the changes introduced in #407: When the parameter is of type `float`, less-capable models sometimes output a `string` or other types that might not be suitable to be converted to a `float`, which will cause the evaluation pipeline to error in `float(value)`. To prevent this, the pipeline now verifies the `value` type before attempting conversion to `float`.
This PR **DOES NOT** change the leaderboard evaluation score.

[BFCL] PR#407 Evaluation Pipeline Robustness Patch

---

berkeley-function-call-leaderboard/README.md
berkeley-function-call-leaderboard/eval_checker/eval_runner_helper.py
berkeley-function-call-leaderboard/model_handler/firework_ai_handler.py
berkeley-function-call-leaderboard/model_handler/handler_map.py

This PR adds firefunction-v2 to the leaderboard. It also updates the fireworks handler making sure that the parameters and prompt are set correctly.

Add firefunction-v2 to the leaderboard

---

berkeley-function-call-leaderboard/README.md
berkeley-function-call-leaderboard/eval_checker/eval_runner_helper.py
berkeley-function-call-leaderboard/model_handler/constant.py
berkeley-function-call-leaderboard/model_handler/granite_handler.py
berkeley-function-call-leaderboard/model_handler/handler_map.py

This PR adds the [granite-20b-functioncalling](https://huggingface.co/ibm-granite/granite-20b-functioncalling) model to the BFCL.
This PR only adds the model handler. The leaderboard should be updated in a separate PR.

[BFCL] add ibm-granite-20b-functioncallling model

---

berkeley-function-call-leaderboard/README.md
berkeley-function-call-leaderboard/model_handler/granite_handler.py

On July 16th, PR #516 and PR #512 were merged first. They introduced fixes that should be applied to all model handlers. Shortly after, on the same day, PR #525 was merged. The new model handler introduced in PR #525 is missing the fixes from the previous two merged PRs (it wasn't synced accordingly). This PR addresses this issue by applying the necessary fixes to the new model handler.

[BFCL] Apply Fix to Newly Introduced Model Handler Missed in Previous PR Merge

---

raft/format.py

This PR addresses an issue with the datapoint field in the formatter for data generation. Specifically, it corrects the column renaming in `format.py` on line 107. The line:
```python
newds = ds.rename_columns({'question': 'prompt', 'cot_answer': 'completion'})
```
has been updated to:
```python
newds = ds.rename_columns({'instruction': 'prompt', 'cot_answer': 'completion'})
```
The change is necessary because the "instruction" field already includes the question. Here is the relevant code snippet that sets the "instruction" field:
```python
context = ""
for doc in docs:
context += "<DOCUMENT>" + str(doc) + "</DOCUMENT>\n"
context += q
datapt["instruction"] = context
```
We want to thank @HuiyingLi for bringing this up. 
Fixes #534.
---------
Co-authored-by: Charlie Cheng-Jie Ji …

[RAFT] Fix Datapoint Field in Formatter for Data Generation

---

berkeley-function-call-leaderboard/README.md
berkeley-function-call-leaderboard/eval_checker/eval_runner.py

- Fixed a small typo in the BFCL readme
- Added a more descriptive error message in eval_runner.py

Add more descriptive error message in eval_runner.py

---

blogs/4_open_functions.html
blogs/7_open_functions_v2.html

The Openfunctions-v2 blog workflow was recommending the `http` endpoint on port `8000`. Since, we migrated to https, the end-point needs to be fixed.
Latest end-point: [https://luigi.millennium.berkeley.edu/v1](https://luigi.millennium.berkeley.edu/v1/chat/completions) 
This PR does not affect the BFCL Leaderboard.

Update 7_open_functions_v2.html with the right url

---

berkeley-function-call-leaderboard/README.md
berkeley-function-call-leaderboard/eval_checker/js_type_converter.py
berkeley-function-call-leaderboard/model_handler/functionary_handler.py
berkeley-function-call-leaderboard/model_handler/nvidia_handler.py

**Issue**: 
Javascript, id: 6 presents a parameter where the js type converter doesn't properly handles, i.e. converting js parameter into python data type,
```javascript
{"initialState": initialStateObject, "reducers": reducersMap, "middlewares": ["loggerMiddleware"], "enhancers": ["applyMiddleware", "myMiddleWare"]}
```
**Solution**:
This PR addresses the proper handling of a dictionary with array values appearing in BFCL. An additional unit test has been added. 
This PR **will** change the leaderboard score.

[BFCL] Fix JS type converter to handle dictionaries with array values

---

berkeley-function-call-leaderboard/openfunctions_evaluation.py

For BFCL generations of hosted models, this will check for rate limit errors and retry thrice. We can choose to include an exponential back-off as is usually recommended, but I think in the interest of keeping it simple this should perhaps be sufficient?
This does NOT affect the leaderboard values.

[BFCL] Handling rate limits

---

blogs/8_berkeley_function_calling_leaderboard.html

[BFCL Blog] Leaderboard Naming Typo 8_berkeley_function_calling_leaderboard.html

---

berkeley-function-call-leaderboard/README.md
berkeley-function-call-leaderboard/eval_checker/eval_runner_helper.py

Changes:
- Fix Functionary Medium 3.1 model version name in `eval_runner_helper.py`
- add readme parallel inference

[BFCL Chore] Fix Functionary Medium 3.1 model name & add readme parallel inference

---

berkeley-function-call-leaderboard/bfcl/model_handler/gorilla_handler.py
berkeley-function-call-leaderboard/bfcl/model_handler/oss_handler.py

Bug fix of #614 [](url)
This pull request resolves the `ModuleNotFoundError` reported in issue #614 by updating the import paths affected by the directory restructuring in commit 70d6722. The adjustments ensure that the LLM inference functionality works as expected.
**Changes:**
- `oss_handler.py` and `gorilla_handler.py` import paths updated to include the new `bfcl` directory prefix.
**Testing:**
Run the following command to verify that the issue has been resolved:
`python openfunctions_evaluation.py --model gorilla-openfunctions-v2 --test-category multiple --num-threads 1
`

Fix issue #614: [BFCL] ModuleNotFoundError after commit 70d6722

---

berkeley-function-call-leaderboard/apply_function_credential_config.py
berkeley-function-call-leaderboard/bfcl/eval_checker/executable_python_function.py

This PR won't impact the leaderboard score.

[BFCL] Hot Fix to Remove Extra Parameters for NoAPIKeyError

---

berkeley-function-call-leaderboard/README.md
berkeley-function-call-leaderboard/bfcl/model_handler/oss_model/glm.py

fixed a bug in the GLM prompt formatting. #637
**The previous formatted prompt:**
`[gMASK]<sop><|user|>\nI'm playing a dice game and want to calculate my chances. I roll the die 20 times, and I'm trying to figure out the probability of landing on a 6 exactly five times, considering each roll has a one in six chance of being a 6. Could you help me with that?<|assistant|>`
the function calling result:
**The fixed formatted prompt:**
Single role: user
```
[gMASK]<sop><|system|>
你是一个名为 ChatGLM 的人工智能助手。你是基于智谱AI训练的语言模型 GLM-4 模型开发的，你的任务是针对用户的问题和要求提供适当的答复和支持
{
"name": "calculate_ROI",
"description": "Calculate the Return on Investment (ROI) for a given investment amount and net profit. Note that the provided function is in Python 3 syntax.",
"parameters": {
"type": "object",
"properties": { …
```

fix: bug for glm prompt format

---

.gitignore
berkeley-function-call-leaderboard/README.md
berkeley-function-call-leaderboard/bfcl/eval_checker/custom_exception.py
berkeley-function-call-leaderboard/bfcl/eval_checker/eval_runner_helper.py
berkeley-function-call-leaderboard/bfcl/model_handler/handler_map.py
berkeley-function-call-leaderboard/bfcl/model_handler/proprietary_model/openai.py
berkeley-function-call-leaderboard/function_credential_config.json

This PR adds new models `o1-preview-2024-09-12` and `o1-mini-2024-09-12` to the leaderboard.

[BFCL] Add New Model `o1-preview-2024-09-12` and `o1-mini-2024-09-12` 

---

raft/raft_local.py

Last time when I contributed the `raft_local.py` in directory named `raft` there was some unnecessary were there, which I removed in this pull request. It will not confuse the developers when they read the file.

removed unnecessary comments in raft/raft_local.py

---

berkeley-function-call-leaderboard/CHANGELOG.md
berkeley-function-call-leaderboard/bfcl/model_handler/utils.py

In the parse_nested_value function, added a check to determine whether we are dealing with another function call or if its a regular dictionary. Previous version of the code incorrectly assumed that this was always a function call and did not consider the case where the function argument is a dictionary. 
Fix https://github.com/ShishirPatil/gorilla/issues/652

[BFCL] Bug Fix parse_nested_value function for model_handler utils

---

blogs/14_agent_arena.html

This is a change made to the blog of Agent Arena - where we redirect users to a different LMSys blog in our Elo section.

[Agent-Arena] Navigate the blog link of LmSys to Elo Blog.

---

berkeley-function-call-leaderboard/CHANGELOG.md
berkeley-function-call-leaderboard/bfcl/model_handler/oss_model/base_oss_handler.py

Fix #649 
Instead of send requests to the vllm server one by one in sequence, we should send all requests all at once to vllm to utiliza its batching and optimizaiton benefits. 
Tested on 8 x A100 (40G) with Llama 3.1 70B. The inference speed on single-turn entries are roughtly the same (within 1 minute difference) as when using `llm.generate` before the BFCL V3 release in #644]. The multi-turn entries still takes around 2 hours to complete, but that's largely due to the nature of the multi-turn dataset; it has been much faster than previously where it would take 2 days to finish.
This PR **will not** affect the leaderboard score.

[BFCL] Speed Up Locally-hosted Model Inference Process

---

berkeley-function-call-leaderboard/bfcl/constant.py
berkeley-function-call-leaderboard/bfcl/eval_checker/eval_runner.py
berkeley-function-call-leaderboard/bfcl/eval_checker/eval_runner_helper.py
berkeley-function-call-leaderboard/bfcl/eval_checker/model_metadata.py
berkeley-function-call-leaderboard/bfcl/eval_checker/multi_turn_eval/func_source_code/gorilla_file_system.py
berkeley-function-call-leaderboard/bfcl/model_handler/handler_map.py
berkeley-function-call-leaderboard/bfcl/model_handler/oss_model/salesforce.py

This PR **will not** affect the leaderboard score. 
- Exclude `multi_turn_composite` from "all" and "multi_turn" categories as it's not currently taken into account when calculating score
- Sort by rank for live and non-live CSV files
- Add descriptive error handling for force-terminated entries
- Improve debug log readability for `Gorilla File Systems` functions
- Suppress print statements in the Salesforce handler
- Set cost to "N/A" for all OSS models

[BFCL] Chore: Various Improvements and Adjustments

---

blogs/13_bfcl_v3_multi_turn.html

Changes: 
- Be clear that BFCL V3 consist of existing datasets from BFCL V1 and V2. BFCL V3 introduces a new category, i.e. multi-turn, multi-step into the mix. 
- Route users to earlier blog posts if they are not familiar with the concept of function calling, and evaluations in single-turn single-step scenarios. These knowledge are foundational and prerequisite for BFCL V3 blog.

[BFCL Blog] BFCL V3 wording refine

---

berkeley-function-call-leaderboard/pyproject.toml

When I tried to run `$ python openfunctions_evaluation.py --model gemini-1.5-pro-002-FC` I got a lot of 
```
Generating results for gemini-1.5-pro-002-FC:   2%|█▋                                                                                                    | 80/4751 [00:49<1:06:42,  1.17it/s]❗️Failed to write result: Object of type RepeatedComposite is not JSON serializable
Generating results for gemini-1.5-pro-002-FC:   2%|█▉                                                                                                      | 89/4751 [00:55<43:43,  1.78it/s]❗️Failed to write result: Object of type RepeatedComposite is not JSON serializable
Generating results for gemini-1.5-pro-002-FC:   2%|█▉ …
```

Update google-cloud-aiplatform dependency

---

berkeley-function-call-leaderboard/bfcl/eval_checker/multi_turn_eval/multi_turn_utils.py

This PR fixes an issue introduced in #724. We need to preserve the original `func_call` to avoid errors during evaluation.
`func_call` should be like `xxxx_instance.cd(folder='document')` so that when `eval(func_call)`, the `cd` method is invoked. Without the patch, `func_call` would become `cd` and thus resulting in variable not found error.

[BFCL] Patch #724

---

berkeley-function-call-leaderboard/bfcl/model_handler/proprietary_model/gemini.py
berkeley-function-call-leaderboard/pyproject.toml

This is to avoid the following error with long context on Gemini models due to insufficient quota:
```
Error: 429 Resource exhausted. Please try again later. Please refer to https://cloud.google.com/vertex-ai/generative-ai/docs/quotas#error-code-429 for more details.
```
This approach uses exponential backoff retries when encountering a ResourceExhausted error.

Add exponential retry logic for gemini models

---

berkeley-function-call-leaderboard/CHANGELOG.md
berkeley-function-call-leaderboard/bfcl/eval_checker/eval_runner_helper.py

There is a duplicate line in the `record_cost_latency` function that would count the input and output token for each entry multiple times. It was due to a merge conflict. 
This PR will not affect the leaderboard score, but will affect the cost and latency info.

[BFCL] Remove Duplicate Line in `record_cost_latency`

---

berkeley-function-call-leaderboard/bfcl/model_handler/proprietary_model/gemini.py

There is a bug in handling examples with no tools / function definitions. Because the tools array is created like this:
```
tools = [Tool(function_declarations=func_declarations)]
```
the following conditional would always submit a tool, since the array has a single element:
```
api_response = self.generate_with_backoff(
client=client,
contents=inference_data["message"],
generation_config=GenerationConfig(
temperature=self.temperature,
),
tools=tools if len(tools) > 0 else None,  # conditional will always resolve to True
)
```
This led to the following Gemini API error when a Tool was submitted with no function declarations:
```
400 Request contains an invalid argument. [detail: "[ORIGINAL ERROR] generic::invalid_argument: The GenerateContentRequest proto is invalid:\n  * …
```

Fix handling of examples with no tools in Gemini

---

berkeley-function-call-leaderboard/bfcl/model_handler/proprietary_model/gemini.py

Even with the current retry logic, I was still facing ResourceExhaustion errors during the multi_turn_long_context cases. I have removed the stop condition in the retry logic to allow the code to continue trying until the tokens per minute quota allows for new requests. This potentially could increase the duration of the test, but it will allow all examples to finish.

Remove stop condition in gemini retry logic

---

berkeley-function-call-leaderboard/CHANGELOG.md
berkeley-function-call-leaderboard/bfcl/eval_checker/eval_runner_helper.py
berkeley-function-call-leaderboard/bfcl/model_handler/proprietary_model/gemini.py

This PR fixes errors where the user adds an empty turn in a multi-turn conversation request, causing the following API error message:
```
InvalidArgument: 400 Please use a valid role: user, model.
```
Gemini sometimes returns an empty content during multi-turn conversations, particularly in response to a function result in the previous turn. 
As a workaround, we can just skip adding this turn and proceed with the next user turn, which should not affect the correctness of the example unless the missing turn was a function call. But generally, it seems that the missing turn is the optional natural language response to the function response.

Skip adding empty content from gemini

---

berkeley-function-call-leaderboard/data/possible_answer/BFCL_v3_java.json
berkeley-function-call-leaderboard/data/possible_answer/BFCL_v3_javascript.json
berkeley-function-call-leaderboard/data/possible_answer/BFCL_v3_live_multiple.json

I found an error ["Invalid value for parameter 'name': 'John Doe'. Expected one of ['j', 'o', 'h', 'n', '', 'd', 'o', 'e']."], in BFCL_v3_live_multiple_score.json.
this is because "John Doe" is not a list. 
`{"id": "live_multiple_189-83-0", "ground_truth": [{"sendHttpRequest": {"method": ["POST"], "url": ["https://httpbin.org/post"], "headers": [{"Content-Type": ["application/json"]}], "data": [{"name": "John Doe", "email": "john.doe@example.com"}]}}]}`
I made a list of all similar errors and fixed them
```
ERROR:root:java_67:[{'APP_NAME': 'PhotoEditor'}, {'IMAGES_ROOT': '/path/to/images'}, {'BACKGROUND_IMAGE_FOLDER': 'background'}, {'BACKGROUND_IMAGE': 'custom-bg.png'}] value is not a list: PhotoEditor
ERROR:root:java_67:[{'APP_NAME': 'PhotoEditor'}, {'IMAGES_ROOT': '/path/to/images'}, …
```

[BFCL] some tiny fix in possible_answer

---

berkeley-function-call-leaderboard/.env.example
berkeley-function-call-leaderboard/CHANGELOG.md
berkeley-function-call-leaderboard/README.md
berkeley-function-call-leaderboard/bfcl/eval_checker/model_metadata.py
berkeley-function-call-leaderboard/bfcl/model_handler/handler_map.py
berkeley-function-call-leaderboard/bfcl/model_handler/model_style.py
berkeley-function-call-leaderboard/bfcl/model_handler/proprietary_model/writer.py
berkeley-function-call-leaderboard/bfcl/model_handler/utils.py
berkeley-function-call-leaderboard/pyproject.toml
raft/azure-ai-studio-ft/howto.md

This PR adds support for Writer models and our latest Palmyra X 004 to BFCL. Thank you!

[BFCL] Add support for Writer models and Palmyra X 004

---

berkeley-function-call-leaderboard/bfcl/__main__.py
berkeley-function-call-leaderboard/bfcl/model_handler/oss_model/deepseek_coder.py

This PR updates the decoding logic for DeepSeek-Coder handler to fix its performance issue in the irrelevance category. 
The irrelevance category metric we use is that, either the `decode_ast` should fail (error) or the decoded output is empty (eg, empty list or empty string). 
For the DeepSeek-Coder model, 
When it outputs a valid function call, the model response will be a list of dictionaries `[{func1:{param1:val1,...}},{func2:{param2:val2,...}}]`, so it's fine for `decode_ast` to just return it without any processing.
However, when the output is a message (not valid function call), under the `_parse_query_response_prompting` logic, the model response will be that message string, and in the current `decode_ast` implementation, that string will just be treated as the decoded output, and …

[BFCL] Fix Irrelevance Category Performance for DeepSeek Coder Handler

---

berkeley-function-call-leaderboard/bfcl/model_handler/proprietary_model/claude.py

This PR updates the `_add_execution_results_prompting` method in Claude handler to have the `content` field in the message be a list of one dictionary `"content": [{"type": "text", "text": "abcd"}]` instead of a string `"content": "abcd"`. Prompt caching expects it in this format.

[BFCL] Minor Fix to Claude Handler for Better Prompt Caching

---

berkeley-function-call-leaderboard/CHANGELOG.md
berkeley-function-call-leaderboard/LOG_GUIDE.md
berkeley-function-call-leaderboard/README.md
berkeley-function-call-leaderboard/bfcl/__main__.py
berkeley-function-call-leaderboard/bfcl/_llm_response_generation.py
berkeley-function-call-leaderboard/bfcl/model_handler/base_handler.py
berkeley-function-call-leaderboard/bfcl/model_handler/oss_model/base_oss_handler.py
berkeley-function-call-leaderboard/bfcl/model_handler/proprietary_model/claude.py
berkeley-function-call-leaderboard/bfcl/model_handler/proprietary_model/cohere.py
berkeley-function-call-leaderboard/bfcl/model_handler/proprietary_model/databricks.py
berkeley-function-call-leaderboard/bfcl/model_handler/proprietary_model/fireworks.py
berkeley-function-call-leaderboard/bfcl/model_handler/proprietary_model/gemini.py
berkeley-function-call-leaderboard/bfcl/model_handler/proprietary_model/gorilla.py
berkeley-function-call-leaderboard/bfcl/model_handler/proprietary_model/mistral.py
berkeley-function-call-leaderboard/bfcl/model_handler/proprietary_model/nexus.py
berkeley-function-call-leaderboard/bfcl/model_handler/proprietary_model/openai.py
berkeley-function-call-leaderboard/bfcl/model_handler/proprietary_model/writer.py
berkeley-function-call-leaderboard/bfcl/model_handler/proprietary_model/yi.py

This pull request improves the accuracy of latency measurement by addressing the following issues:
1. **Retry Latency Handling:** Previously, when a retry occurred, the reported latency included the duration from the first attempt to the final successful attempt, resulting in inflated latency values. This change ensures that only the latency of the final successful attempt is measured. This adjustment primarily impacts the Gemini and Claude models.
2. **Preprocessing Time Exclusion:** For models requiring preprocessing before hitting their endpoints, this preprocessing time is now excluded from the reported latency, ensuring a more accurate reflection of the actual request duration.
Additionally, the `state_log` is now included as part of the `inference_log` by default. Users can disable …

[BFCL] Improve Latency Measurement Accuracy and Enable Default State Logging

---

blogs/12_bfcl_v2_live.html

There were some number of entries changes that were introduced in the previous dataset fix PRs (such as #789). This PR updates the blog to have the up-to-date data composition number.

[BFCL Blog] Update BFCL V2 Blog with Latest Data Composition Number

---

berkeley-function-call-leaderboard/CHANGELOG.md
berkeley-function-call-leaderboard/SUPPORTED_MODELS.md
berkeley-function-call-leaderboard/bfcl/eval_checker/model_metadata.py
berkeley-function-call-leaderboard/bfcl/model_handler/handler_map.py
berkeley-function-call-leaderboard/bfcl/model_handler/oss_model/llama.py

Add the following new models to the leaderboard:
- `meta-llama/Llama-3.3-70B-Instruct-FC`
- `meta-llama/Llama-3.3-70B-Instruct`
From the [model card](https://www.llama.com/docs/model-cards-and-prompt-formats/llama3_3#-prompt-template-):
> Llama 3.3 uses the same prompt format as Llama 3.1. Prompts written for Llama 3.1 work unchanged with Llama 3.3.
> Llama 3.3 also supports the same code-interpreter and tool-calling capabilities as Llama 3.1.
So we have llama 3.3 use the same handler as llama 3.1 series.

[BFCL] Add New Model `Llama-3.3-70B-Instruct`, `Llama-3.3-70B-Instruct-FC`

---

berkeley-function-call-leaderboard/CHANGELOG.md
berkeley-function-call-leaderboard/SUPPORTED_MODELS.md
berkeley-function-call-leaderboard/bfcl/eval_checker/model_metadata.py
berkeley-function-call-leaderboard/bfcl/model_handler/handler_map.py
berkeley-function-call-leaderboard/bfcl/model_handler/oss_model/mistral_fc.py

This PR adds new model `mistralai/Ministral-8B-Instruct-2410` to the leaderboard. Since this model is open-sourced on huggingface, a local-serving mistral handler is also added; this is different from the `mistral.py` in `proprietary_model` folder, which does inference through their API endpoint.

[BFCL] Add Mistral Local Serving Handler and Add New Model `mistralai/Ministral-8B-Instruct-2410`

---

berkeley-function-call-leaderboard/bfcl/model_handler/api_inference/claude.py
berkeley-function-call-leaderboard/bfcl/model_handler/api_inference/cohere.py
berkeley-function-call-leaderboard/bfcl/model_handler/api_inference/deepseek.py
berkeley-function-call-leaderboard/bfcl/model_handler/api_inference/gemini.py
berkeley-function-call-leaderboard/bfcl/model_handler/api_inference/nova.py
berkeley-function-call-leaderboard/bfcl/model_handler/api_inference/openai.py
berkeley-function-call-leaderboard/bfcl/model_handler/utils.py

This PR introduces the retry_with_backoff mechanism for Nova models to address throttling issues when calling the AWS Bedrock endpoint. 
Because Bedrock does not throw a dedicated throttling exception ([link](https://docs.aws.amazon.com/ja_jp/bedrock/latest/APIReference/CommonErrors.html)), the existing decorator was updated to allow custom retry conditions driven by exception messages. 
Additionally, type hints and improved docstrings have been added to enhance maintainability and readability.

[BFCL Chore] Implement `retry_with_backoff` for Amazon Nova Handler

---

berkeley-function-call-leaderboard/CHANGELOG.md
berkeley-function-call-leaderboard/SUPPORTED_MODELS.md
berkeley-function-call-leaderboard/bfcl/eval_checker/model_metadata.py
berkeley-function-call-leaderboard/bfcl/model_handler/handler_map.py

Adds support for [Qwen/QwQ-32B-Preview](https://huggingface.co/Qwen/QwQ-32B-Preview) and [NovaSky-AI/Sky-T1-32B-Preview](https://huggingface.co/NovaSky-AI/Sky-T1-32B-Preview) 
Since both the reasoning models are finetunes of Qwen/Qwen2.5-32B-Instruct, I've used the `QwenHandler` for both. (Neither model has any special finetuning for tool use AFAIK)

Add support for QwQ and Sky-T1-32B-Preview

---

berkeley-function-call-leaderboard/CHANGELOG.md
berkeley-function-call-leaderboard/SUPPORTED_MODELS.md
berkeley-function-call-leaderboard/bfcl/eval_checker/model_metadata.py
berkeley-function-call-leaderboard/bfcl/model_handler/handler_map.py
berkeley-function-call-leaderboard/bfcl/model_handler/local_inference/base_oss_handler.py
berkeley-function-call-leaderboard/bfcl/model_handler/local_inference/bielik.py
berkeley-function-call-leaderboard/bfcl/model_handler/local_inference/quick_testing_oss.py

Adding Handler for Open Source LLM Bielik available on HF - https://huggingface.co/speakleash/Bielik-11B-v2.3-Instruct .
I chose to load tokenizer in the constructor of the handler, so that I automatically apply chat template. As a result, I can reuse this handler for models with various templates.

add handler for Bielik

---

berkeley-function-call-leaderboard/bfcl/eval_checker/eval_runner.py

In the result files, the IDs are zero-indexed, whereas in the score files, they are one-indexed. This PR updates the IDs in the score files to match the evaluation IDs in the result JSONs (e.g., `exec_multiple_0`). This alignment ensures consistency and makes it easier to compare the two files.

[BFCL Chore] Align Score File `id` with Result File Test Case IDs

---

berkeley-function-call-leaderboard/bfcl/model_handler/utils.py

I've updated `utils.py` in BFCL to reflect some needed changes to how tools are constructed when using Writer's models such as Palmyra X 004.
cc @HuanzhiMao

[BFCL] Update tool construction for Palmyra models

---

berkeley-function-call-leaderboard/CHANGELOG.md
berkeley-function-call-leaderboard/SUPPORTED_MODELS.md
berkeley-function-call-leaderboard/bfcl/eval_checker/model_metadata.py
berkeley-function-call-leaderboard/bfcl/model_handler/constant.py
berkeley-function-call-leaderboard/bfcl/model_handler/handler_map.py
berkeley-function-call-leaderboard/pyproject.toml

Add the following new models to the leaderboard:
- `gpt-4.5-preview-2025-02-27`
- `gpt-4.5-preview-2025-02-27-FC`
This PR also upgraded `openai` library to version `1.65.0`.

[BFCL] Add New Model `gpt-4.5-preview-2025-02-27`, `gpt-4.5-preview-2025-02-27-FC`

---

berkeley-function-call-leaderboard/bfcl/eval_checker/eval_runner.py

Small fix for when `--score-dir` is passed as an argument to `bfcl evaluate`.

[BFCL] fix bug in how score_dir is handled for bfcl evaluate

---

berkeley-function-call-leaderboard/CHANGELOG.md
berkeley-function-call-leaderboard/SUPPORTED_MODELS.md
berkeley-function-call-leaderboard/bfcl/constants/eval_config.py
berkeley-function-call-leaderboard/bfcl/eval_checker/model_metadata.py
berkeley-function-call-leaderboard/bfcl/model_handler/handler_map.py

Hello from Cohere 👋 
This PR submits our latest model - [Command A](https://cohere.com/blog/command-a). When I ran this against [f81063](https://github.com/ShishirPatil/gorilla/commit/f8106312357d2e687a905610fe972b64482ab8e2) I got the following score, and hopefully you'll be able to reproduce them:
```
| Overall Acc | Model          | Model Link                        | Cost ($ Per 1k Function Calls) | Latency Mean (s) | Latency Standard Deviation (s) | Latency 95th Percentile (s) | Non-Live AST Acc | Non-Live Simple AST | Non-Live Multiple AST | Non-Live Parallel AST | Non-Live Parallel Multiple AST | Non-Live Exec Acc | Non-Live Simple Exec | Non-Live Multiple Exec | Non-Live Parallel Exec | Non-Live Parallel Multiple Exec | Live Acc | Live Simple AST | Live Multiple AST | Live …
```

Add Cohere Command A

---

berkeley-function-call-leaderboard/bfcl/eval_checker/executable_eval/data/executable_python_function.py

Executable evals fail sometimes with the following returned as the response: `{"Response":"False","Error":"Invalid API key!"}`
See this for context: https://github.com/omdbapi/OMDb-API/issues/311#issuecomment-2138657319.

[BFCL] Use HTTPS instead of HTTP for OMDB

---

berkeley-function-call-leaderboard/bfcl/model_handler/api_inference/gemini.py

When the Vertex AI endpoint exceeds its quota, it now raises a `google.api_core.exceptions.TooManyRequests` exception. This PR updates the `retry_with_backoff` function to include this exception type as well.

[BFCL] Update Retry Logic for Gemini Models

---

berkeley-function-call-leaderboard/CHANGELOG.md
berkeley-function-call-leaderboard/CONTRIBUTING.md
berkeley-function-call-leaderboard/SUPPORTED_MODELS.md
berkeley-function-call-leaderboard/bfcl/constants/model_metadata.py
berkeley-function-call-leaderboard/bfcl/model_handler/handler_map.py
berkeley-function-call-leaderboard/bfcl/model_handler/local_inference/llama.py
berkeley-function-call-leaderboard/bfcl/model_handler/local_inference/llama_3_1.py

Address #978 
This PR adds support for the following models, with self-hosted inference method:
- `meta-llama/Llama-4-Scout-17B-16E-Instruct-FC`
- `meta-llama/Llama-4-Maverick-17B-128E-Instruct-FP8-FC`

[BFCL] Add New Models `Llama-4-Scout`, `Llama-4-Maverick`

---

berkeley-function-call-leaderboard/bfcl/constants/model_metadata.py

Fix Typo in Model Name for `xLAM-2-8b-fc-r`

---

berkeley-function-call-leaderboard/pyproject.toml

This PR bumps the `writer-sdk` version to `2.1.0` to solve the following error, which has recently appeared. 
```
Traceback (most recent call last):
....
File ".../gorilla/berkeley-function-call-leaderboard/bfcl/model_handler/api_inference/writer.py", line 13, in __init__
self.client = Writer(api_key=os.getenv("WRITER_API_KEY"))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/anaconda3/lib/python3.11/site-packages/writerai/_client.py", line 102, in __init__
super().__init__(
File "/opt/anaconda3/lib/python3.11/site-packages/writerai/_base_client.py", line 858, in __init__
self._client = http_client or SyncHttpxClientWrapper(
^^^^^^^^^^^^^^^^^^^^^^^
File "/opt/anaconda3/lib/python3.11/site-packages/writerai/_base_client.py", line 756, in __init__
super().__init__(**kwargs) …
```

Bump `writer-sdk` Dependency Version

---

.github/workflows/bfcl-pipy-release.yml
berkeley-function-call-leaderboard/pyproject.toml

- Introduces `Publish BFCL to PyPI` GitHub Action.
- Runs on pushes to the main branch and merged PRs.
- Auto-generates CalVer-serial version, builds sdist + wheel, and uploads via pypa/gh-action-pypi-publish

[BFCL] CI: Add “Publish to PyPI” workflow with CalVer-serial auto-versioning

---

berkeley-function-call-leaderboard/bfcl_eval/model_handler/parser/java_parser.py
berkeley-function-call-leaderboard/bfcl_eval/model_handler/parser/js_parser.py

for the Java and JavaScript parsers, I updated the error handling such that it returns a `SyntaxError` rather than an `Exception`.
- this is done in parallel with using `bfcl` to evaluate models, raising a specific type of error works better to handle erroneous model responses (as opposed to runtime errors that are unrelated to the model itself)
- `SyntaxError` may be too narrow of a scope
if there is another error type that is more relevant, I'm glad to make the changes needed on my side
thanks in advance!

[BFCL] Replace Exception with SyntaxError for Java and JavaScript Parsers

---

berkeley-function-call-leaderboard/CHANGELOG.md
berkeley-function-call-leaderboard/bfcl_eval/model_handler/local_inference/qwen.py
berkeley-function-call-leaderboard/bfcl_eval/model_handler/local_inference/qwen_fc.py

This PR fixes an issue where the special token `<|im_end|>\n` was being incorrectly added using. This operation does not modify `formatted_prompt` in-place, which can lead to the token not being appended as expected. 
**Changes**
Replaced `formatted_prompt + "<|im_end|>\n"` with `formatted_prompt += "<|im_end|>\n"` to ensure proper in-place string concatenation.
**Note**
This issue significantly affects `Qwen3` model performance in the leaderboard.

[BFCL] Fix prompt concatenation bug in Qwen template

---

.github/workflows/bfcl-pipy-release.yml
berkeley-function-call-leaderboard/CHANGELOG.md

This PR modifies the GitHub Actions workflow to ensure it only runs on the main (source) repository and not on forks. Forks of this repository do not have the necessary permissions or secrets for publishing to PiPy, and attempting to run the workflow on those forks results in guaranteed failures. This helps keep the CI clean.

Restrict GitHub Actions Workflow to Run Only on Source Repository

---

berkeley-function-call-leaderboard/bfcl_eval/_llm_response_generation.py
berkeley-function-call-leaderboard/bfcl_eval/model_handler/local_inference/base_oss_handler.py

When the generation pipeline encounters an exception, this PR ensures that the traceback is printed directly to the terminal, in addition to being logged to the local result file. This allows developers to immediately view and debug errors in real-time.

[BFCL] nit: Print traceback on generation error

---

berkeley-function-call-leaderboard/bfcl_eval/model_handler/local_inference/qwen.py
berkeley-function-call-leaderboard/bfcl_eval/model_handler/local_inference/qwen_fc.py

1. Reasoning content was not being added in the inference data for both QwenHandler and QwenFCHandler.
2. The _format_prompt function in QwenFCHandler was not checking for tool_calls in assistant messages. All those messages where the assistant requested a tool call were converted to empty messages.
This PR fixes both the above points.
This also means that all those scores for qwen3-prompt and qwen3-FC that were calculated using local_inference, would need to be calculated again.

Fix qwen3 inference data and qwenfc handler chat template

---

berkeley-function-call-leaderboard/CHANGELOG.md
berkeley-function-call-leaderboard/README.md
berkeley-function-call-leaderboard/bfcl_eval/__main__.py
berkeley-function-call-leaderboard/bfcl_eval/eval_checker/eval_runner.py

This PR fixes issue #1159 where running evaluation with a subset of IDs caused:
**AssertionError: The length of the model result (1) does not match the length of the prompt (400) or possible answer (400).**
1. Introduces `--partial-eval` to the CLI so users can deliberately score an incomplete result file.
2. Realigns prompts / ground-truth rows to the IDs present in the model result via the new helper `_subset_entries_by_model_ids`.
3. Improves error handling – when `--partial-eval` is not supplied, a clear `ValueError` explains the remedy instead of a generic assertion.
- Verified that evaluation now succeeds when generating only a subset of IDs.
Fixes #1159

[BFCL] Add `--partial-eval` flag for subset evaluation and fix length-mismatch AssertionError (#1159)

---

berkeley-function-call-leaderboard/bfcl_eval/data/possible_answer/BFCL_v4_simple_javascript.json

Fix #1168 
Updates the IDs in the `BFCL_v4_simple_javascript.json` dataset to be consistent with naming conventions, from the format `simple_javascript__<n>` to `simple_javascript_<n>`.

Fix dataset ID format in `BFCL_v4_simple_javascript.json`
