ShishirPatil/gorilla

README.md
eval/README.md
requirements.txt

Update the evaluation dpendencies

Update the evaluation dependencies

---

.github/ISSUE_TEMPLATE/apibench.md
.github/ISSUE_TEMPLATE/custom-template.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/hosted-gorilla-.md

Update issue templates

---

eval/README.md

fix relative path in gorilla/eval/README.md

fix relative path in gorilla/eval/README.md

---

README.md
eval/README.md
inference/README.md
inference/apply_delta.py
inference/example_questions/example_questions.jsonl
inference/gorilla_eval.py
inference/requirements.txt

In this PR we release the first set of weights for Gorilla 🎉  
It chooses from 925 HF APIs in a 0-shot fashion (without any retrieval). In the spirit of being open, we do not filter, nor carry out any post processing either to the prompt nor response 🎁 We will release TorchHub, TensorFlow, and the combined {HF+TF+TH} model weights also. Keep in mind that `gorilla-7b-hf-v0` does not have any generic chat capability. We do have a model with all the 1600+ APIs which also has generic chat capability, which we release slowly to accommodate server demand. 
You can play around with Gorilla either through our hosted colab (OpenAI Chat completion API compliant)  or you can download and run it locally. 
Thank you for all the comments and suggestions so far! Keep them coming!!!
🚀 🚀 🚀

🦍  Release gorilla-7b weights for HuggingFace APIs 🤗 

---

.gitignore
data/apizoo/shawnharmsen1.json

was looking to contribute some apis and realized you just want the json submitted as an issue?
in meantime please some love for jetbrains you vscode enjoooooyers <3
EDIT:
I added it in the pr please let me know what you prefer

json contribution gpt4all

---

inference/gorilla_eval.py

Ref: #18 
We haven't added support for Apple's MPS for inference. Contributions welcome!

remove `replace_llama_attn_with_non_inplace_operations` as we don't supported it yet

---

README.md
inference/README.md
inference/requirements.txt
inference/serve/conv_template.py
inference/serve/gorilla_cli.py

update the cli serving for gorilla-7b-hf-v0

Update cli serving for gorilla

---

eval/get_llm_responses.py

Fixed typo - Update get_llm_responses.py

---

inference/README.md

Fix typo in inference/README.md

---

README.md
inference/README.md
inference/serve/conv_template.py
inference/serve/gorilla_falcon_cli.py

In this PR we release the weights for Gorilla 0-shot model for Hugging Face Hub APIs with MPT-7B and Falcon-7B base models 🎉
It chooses from 925 HF APIs in a 0-shot fashion (without any retrieval). We do not filter, nor carry out any post processing either to the prompt nor response. You can play around with Gorilla either through our hosted colab (OpenAI Chat completion API compliant) or you can download the weights and run it locally.
As always, thank you for all the comments and suggestions so far! Keep them coming!!!
🚀 🚀 🚀

🟢 Releasing Apache 2.0 models MPT/Falcon

---

inference/README.md

Fix broken url references to model weights and jsonl with example questions.

Broken links

---

index.html

Updating the gh-pages static website. 
+ Added spotlight demo video
+ Overhauled the webpage to make it more streamlined

Web rehaul

---

README.md

https://github.com/gorilla-llm/gorilla-cli

Update README about gorilla-cli release

---

eval/get_llm_responses.py
eval/get_llm_responses_retriever.py

changed according to Anthropic [repository](https://github.com/anthropics/anthropic-sdk-python)

update(anthropic):  #63 to (0.3.x)

---

README.md

The WebUI implementation is progressing well. I'm currently in the process of adding the model selection dropdown, per your suggestion. However, handling the varied output styles of different models is taking a bit longer than anticipated due to the need for regex customization. Rest assured, I'm diligently working on this aspect.
Just making this available so that this is accessible to people as early as possible. Will get the other parts done soon!
Also had to ask do I upload the python notebook to the repository too?

PR for Gradio WebUI Feature ([feature] Gradio webui - #102)

---

eval/eval-scripts/ast_eval_hf.py
eval/eval-scripts/codebleu/bleu.py
eval/eval-scripts/codebleu/dataflow_match.py
eval/eval-scripts/codebleu/parser/DFG.py
eval/eval-scripts/codebleu/syntax_match.py
eval/eval-scripts/codebleu/utils.py

sentence optimization in docstring and examples

---

blog.html
blogs/6_api_zoo.html

Minor fix to the API Zoo blog title.

Fix the API Zoo blog title

---

index.js

Update backend to `https` so it can receive and serve `https`

Update index.js to support https on backend

---

blog.html
blogs/8_berkeley_function_calling_leaderboard.html

Minor fixes for blog landing page

Fix blog link issues and blog 8 formatting issues

---

assets/css/common-styles.css
assets/css/model_info_dashboard.css
blogs/8_berkeley_function_calling_leaderboard.html

https://github.com/ShishirPatil/gorilla/assets/55744150/e2d9ad50-2e31-455d-9997-cee97712dbe3
Fixed mobile optimization issue in blog 8 from PR #224

Fixed blog 8 mobile optimization

---

index.js
leaderboard.html

This PR fixes the typo made in the leaderboard in #238 . 
This PR also fixed a bug with the voting feature.

Patch for typo made in #238, voting feature fix

---

berkeley-function-call-leaderboard/README.md

Correction for BFCL README, in total 4 APIs to fill out.

Update BFCL README.md

---

assets/css/leaderboard.css
index.js
leaderboard.html

This PR adds the sorting feature to the leaderboard table. By default, the table is sorted by rank.

Add sorting feature to leaderboard table 

---

assets/css/leaderboard.css
index.js
leaderboard.html

This PR Fix Clerical Error in Simple Function (Evaluation by execution) for the leaderboard.

Fix: Clerical Error in Simple Function (Evaluation by execution)

---

assets/css/leaderboard.css
index.js
leaderboard.html

This PR Fix Cascading error resulting from silent error in Vertex AI API innovation in Leaderboard pipeline

Fix: Cascading error resulting from silent error in Vertex AI API innovation in Leaderboard pipeline

---

openfunctions/README.md
openfunctions/inference_local.py
openfunctions/openfunctions_utils.py

- Robustified local inference script, tested both host script and local inference script on server, and dependencies and logic bug fixed
- Add more detailed README

Local inference script tested, bug fixed

---

README.md

Updating stale project roadmap to also include Openfunctions effort and Berkeley Function Calling Leaderboard

Update project roadmap and repository structure

---

leaderboard.html

This PR updates leaderboard with 3 new models
1. claude-3-opus-20240229 (prompting)
2. claude-3-sonnet-20240229 (prompting)
3. meetkai/functionary-medium-v2.2 (function calling)
Note: claude-3 also supports function-calling. But, we decided to include prompting results to give claude the benefit of doubt, given prompting performed better than function-calling.
This PR builds upon recent leaderboard bug fix #253

[Leaderboard Update] Claude-3 Series + MeetKai/Functionary

---

index.js
leaderboard.html

This PR fix a typo that is introduced in #253 , which caused the sorting feature on leaderboard to not work. 
This PR also adds new model to the wagon wheel.

Fix Leaderboard Sorting Issue

---

data/apizoo/Datadog_API.json

Exhaustively added Datadog API to API Zoo

Adding Datadog API to API Zoo

---

index.js

This PR changes the order of the wagon wheel data in a way that groups models from the same company together, so that it is more user-friendly to find the model they want. 
This PR also fixes a typo in the label. Thanks @CharlieJCJ

Reorder Wagon Wheel & Typo Fix

---

index.js

This PR fixes an indexing issue, where the license and Overall accuracy were interlinked.
This does not change the values of the leaderboard.

Bug Fix for Leaderboard

---

raft/raft.py

- changed `for chunk in chunks[:3]:` in `get_chunks` to `for chunk in chunks:` (originally kept to first 3 chunks for testing purposes)
- added instruction to the model to include only the questions in its response for `generate_instructions_gen`
- updated an inline comment to reflect the correct variable name
- removed a debug print statement

removed testing code

---

blogs/7_open_functions_v2.html

Blog 7 Fix: fixed navbar and changed font to source sans pro

---

raft/eval.py
raft/raft.py

feat: more type annotations for the functions

---

leaderboard.html

This PR adds SEO for the name "Berkeley Tool Calling Leaderboard"

Add SEO for Berkeley Tool Calling Leaderboard

---

inference/README.md
openfunctions/utils/java_parser.py
openfunctions/utils/js_parser.py

- Remove Large File, 66.3MB gif from `./inference`, and linked from another github repo

Remove Large File from `./inference`

---

assets/css/leaderboard.css
index.js
leaderboard.html

This PR swap the license and org column with the cost and latency column on the leaderboard. 
Does it change the leaderboard values? 
No

Change column order in leaderboard

---

assets/css/leaderboard.css
index.js
leaderboard.html

Reverts ShishirPatil/gorilla#303 The Wagon wheel needs the column ordering to be changed @HuanzhiMao

Revert "Change column order in leaderboard"

---

assets/css/leaderboard.css

This PR changed the column colour for the leaderboard to make it more visually appealing. 
This PR **does not** change the leaderboard value.

Change column colour for leaderboard

---

assets/css/blog.css
assets/css/styles.css
blogs/4_open_functions.html
blogs/5_how_to_gorilla.html

This PR fix the rendering issue introduced in #307 .
It **does not** change the leaderboard value.

fix blog rendering issue

---

blogs/1_gorilla_intro.html
blogs/4_open_functions.html
blogs/5_how_to_gorilla.html
blogs/7_open_functions_v2.html
blogs/8_berkeley_function_calling_leaderboard.html
blogs/9_raft.html
index.html
leaderboard.html

This PR updates the discord link across all websites (including the leaderboard and all blogs) to make it never expires and has no max-user limit. 
This PR **does not** change the leaderboard score.

Update discord link across all websites

---

goex/.env.example
goex/README.md
goex/cli.py
goex/examples.py
goex/exec_engine/api_executor.py
goex/exec_engine/pipeline.py
goex/main.py
goex/server.py

- Respect `model` parameter in `user_config.json`, passing it down from the CLI to where `chat_completion` is called
- Added python3 venv as another virtual environment option
- Added missing file dependencies
- Nit refactor for the README

Goex Release Refactor

---

blog.html
blogs/10_gorilla_exec_engine.html

Blog Preview Fix:
Mobile View Fix:

GoEx Blog Title and Formatting Fixes

---

.gitignore
goex/exec_engine/docker_sandbox.py

Adds `__init__.py` so that the necessary packages get picked up by `setuptools.find_packages`.

GoEx Import Issues

---

berkeley-function-call-leaderboard/eval_checker/eval_runner_constant.py
berkeley-function-call-leaderboard/eval_checker/eval_runner_helper.py
berkeley-function-call-leaderboard/model_handler/oss_handler.py

This PR fixed a circular import issue introduced by the merging of #327 and #318.
This PR is just a bug-fix PR, and will not affect the BFCL leaderboard score.

Fix Circular Import Issue for BFCL evluation pipeline

---

assets/css/Highlight-Clean.css
blogs/8_berkeley_function_calling_leaderboard.html
index.html

In this PR: 
1. Update the evaluation metric for BFCL, in sync with #377.
2. Change the button layout on the landing page. 
This PR **does not** change the leaderboard value.

Gorilla Website Update April 22nd 

---

assets/css/leaderboard.css
assets/css/model_info_dashboard.css
index.js

This PR aims to improve the user experience when interacting with the wagon wheel on the BFCL leaderboard. Due to the huge number of entries, the wagon wheel is having a hard time displaying them all. This PR addresses the issue for laptop users. This issue still exists on mobile, and we will tackle it later. 
This PR **DOES NOT** change the leaderboard score.

Improve User Experience for Wagon Wheel

---

index.html

This PR adds Xin Wang and Joseph E. Gonzalez to the author section on the Gorilla Project landing page.
This PR **DOES NOT** change the leaderboard value.

[Landing Page] Update Author Info

---

berkeley-function-call-leaderboard/model_handler/nexus_handler.py

Hello! 
I just had a chance to take a look at the handler code for one of the open source models for Raven, and noticed a few things that could be fixed. I have made some fixes here, including fixes for converting the typescript Function Calling DSL into Python Function Calling DSL. This PR is for fixing the prompting issues only.
I believe this logic can be used for other Prompt-based models as well. I notice you ask the model to generate Python outputs but give JSON inputs for prompt-based FC; this can be applied to standardize the prompting side for these other models as well.
I believe there are further fixes necessary on the AST parsing of the outputs that can further improve the performance of the model. Happy to help contribute more there!
I ran the model with these changes, and …

Fixes For NexusHandler

---

berkeley-function-call-leaderboard/model_handler/gpt_handler.py

No other handler includes this
Co-authored-by: Anish <anish.palakurthi@gmail.com>

Remove redundant tokens from GPT-handler

---

goex/README.md
goex/cli.py
goex/docker/docker/dockerfile
goex/docker/mysql_docker/dockerfile
goex/docker/sqllite_docker/dockerfile

- Fixes a bug where undoing a database call would not actually go through occasionally
- Added additional steps in the README to streamline onboarding
- Finished all platform instructions for mkcert install
- Fixes issue with Docker build failing for newer Ubuntu images upon pip installing without a venv

[GoEx] Undo Minor Bug Fix + README Minor Improvement

---

berkeley-function-call-leaderboard/README.md
berkeley-function-call-leaderboard/eval_checker/eval_runner_helper.py
berkeley-function-call-leaderboard/model_handler/handler_map.py
berkeley-function-call-leaderboard/model_handler/nvidia_handler.py

This PR will add ability to inference on Nemotron via Nvidia NIM. It's open source and hosted by Nvidia without specifying the price per inference call. Therefore, no cost per thousand function calls will be recorded. Model result will be updated in a separate PR.

[BFCL] Add ability to evaluate Nemotron-4-340B-Instruct

---

berkeley-function-call-leaderboard/README.md
berkeley-function-call-leaderboard/eval_checker/eval_runner_helper.py
berkeley-function-call-leaderboard/model_handler/constant.py
berkeley-function-call-leaderboard/model_handler/glm_handler.py
berkeley-function-call-leaderboard/model_handler/handler_map.py

This PR added support for inference GML-4-9B via vLLM and deploying the model locally. The function calling feature was achieved through its [tokenizer](https://huggingface.co/THUDM/glm-4-9b-chat/blob/75792d7ee58a335df6943c5d719cc559b64f8e2a/tokenization_chatglm.py#L173). 
The PR **will** change the leaderboard standing and a separate PR will be used to update the leaderboard.

[BFCL] Add Support for GLM-4-9B function calling inference

---

blog.html

[Blog] Fix minor blog 11 date typo

---

blogs/12_bfcl_v2_live.html

Fixed simple function plotly key name from `Python Simple Function AST` to `Simple Function AST`

[BFCL Blog] Hot Fix Plotly Key Name for Simple Function

---

.github/ISSUE_TEMPLATE/bfcl.md

Creates a new issue template. 
DOES not change BFCL leaderboard values.

Create an issue template for BFCL

---

blog.html
leaderboard.html

Update the title and description with V3.

[BFCL] Leaderboard Update: Title and Description Updated to be V3

---

blogs/13_bfcl_v3_multi_turn.html
leaderboard.html

This PR fixed some outdated links on the leaderboard, and updated wording on the blog. 
This PR **does not** change the leaderboard score.

[BFCL Website] Fix Outdated Link; Blog Wording Update

---

blogs/12_bfcl_v2_live.html
blogs/13_bfcl_v3_multi_turn.html
blogs/8_berkeley_function_calling_leaderboard.html
leaderboard.html

Since we separate out the change log file in #648, all the URL links that point to the change log in the leaderboard and blogs need to be updated. 
This PR **will not** change the leaderboard score.

[BFCL Website] Update Change Log Links

---

berkeley-function-call-leaderboard/bfcl/model_handler/base_handler.py

There are some dataset format issues for the single turn entries. The code wraps the question field in an additional unnecessary list.
Fix #651

[BFCL] Bug Fix inference_single_turn_FC function for base_handler

---

berkeley-function-call-leaderboard/bfcl/eval_checker/multi_turn_eval/func_source_code/travel_booking.py

[BFCL] Small typo in variable name in travel_booking.py

---

berkeley-function-call-leaderboard/bfcl/eval_checker/eval_runner.py

Removed the duplicate `main()` function in `bfcl/eval_checker/eval_runner.py`

[BFCL] Remove duplicate in eval_runner.py

---

berkeley-function-call-leaderboard/bfcl/model_handler/oss_model/base_oss_handler.py

[BFCL] Robustness Patch for `_multi_threaded_inference`

---

berkeley-function-call-leaderboard/CHANGELOG.md
berkeley-function-call-leaderboard/bfcl/eval_checker/model_metadata.py
berkeley-function-call-leaderboard/bfcl/model_handler/handler_map.py

This PR adds the model `Qwen/Qwen2.5-72B-Instruct` to the leaderboard.

[BFCL] Add New Model `Qwen/Qwen2.5-72B-Instruct`

---

index_main.js

This PR fixed the issue of the relevance category column not being properly displayed.

[Website] Fix Misalign UI

---

blogs/13_bfcl_v3_multi_turn.html
leaderboard.html

This PR revamped the BFCL V3 Blog to make it clearer and more comprehensive.

[BFCL Blog] Revamp v3 Multi Turn Blog

---

berkeley-function-call-leaderboard/CHANGELOG.md
berkeley-function-call-leaderboard/bfcl/model_handler/constant.py

Been working with Huanzhi over email and noticed this typo

Fix minor typo in default system prompt without func

---

berkeley-function-call-leaderboard/CHANGELOG.md
berkeley-function-call-leaderboard/SUPPORTED_MODELS.md
berkeley-function-call-leaderboard/bfcl/eval_checker/model_metadata.py
berkeley-function-call-leaderboard/bfcl/model_handler/handler_map.py

Models and paper were renamed after release.

Rename CALM to CoALM

---

berkeley-function-call-leaderboard/CHANGELOG.md
berkeley-function-call-leaderboard/SUPPORTED_MODELS.md
berkeley-function-call-leaderboard/bfcl/eval_checker/model_metadata.py
berkeley-function-call-leaderboard/bfcl/model_handler/handler_map.py

Adding the Bittensor Subnet 20 (BitAgent) generated 8B parameter model for evaluation

Bitagent 8b submission

---

berkeley-function-call-leaderboard/bfcl/eval_checker/multi_turn_eval/func_source_code/gorilla_file_system.py
berkeley-function-call-leaderboard/bfcl/eval_checker/multi_turn_eval/func_source_code/trading_bot.py
berkeley-function-call-leaderboard/bfcl/eval_checker/multi_turn_eval/func_source_code/travel_booking.py
berkeley-function-call-leaderboard/bfcl/eval_checker/multi_turn_eval/func_source_code/vehicle_control.py

Make all import paths absolute, as recommended by PEP8.

Make all import paths absolute.

---

berkeley-function-call-leaderboard/bfcl/eval_checker/eval_runner.py
berkeley-function-call-leaderboard/bfcl/eval_checker/eval_runner_helper.py

This change exposes an API for 3P code to run the evaluation of a single task, while also improving code readability.

Move logic to eval a task in a separate function.

---

berkeley-function-call-leaderboard/CONTRIBUTING.md
berkeley-function-call-leaderboard/README.md
berkeley-function-call-leaderboard/bfcl/constants/model_metadata.py
berkeley-function-call-leaderboard/bfcl/eval_checker/eval_runner_helper.py

Moved `model_metadata.py` to improve code structure. Updated corresponding docs.

[BFCL] Move `model_metadata.py` to `constants` folder

---

berkeley-function-call-leaderboard/SUPPORTED_MODELS.md

Organized models by:
- Base Model: The canonical name of the large language model (LLM), including versioning if applicable.
- Type: Denotes the interaction mode supported by the model: either Function Calling or Prompt.
- Provider: The organization responsible for providing access to the model: cloud providers (e.g., OpenAI, Anthropic), companies (e.g., Cohere, Mistral AI), or Self-hosted 💻 for models running locally or on private infrastructure.
- ID on BFCL: Full unique identifier used in BFCL for reference.

Reformatted Supported Model Table

---

openfunctions/README.md
openfunctions/requirements.txt
openfunctions/utils/java_parser.py
openfunctions/utils/js_parser.py

fix treesitter setup

---

berkeley-function-call-leaderboard/bfcl_eval/constants/model_config.py

Hi Team,
This PR adds the `RZN-T` model to the leaderboard.
* Base Model: Qwen 3 0.6 B
* Fine-Tuning: GRPO for improved tool calling
* Model Link: https://huggingface.co/phronetic-ai/RZN-T
* Dependencies: As specified in the original `pyproject.toml` 
I made the inclusion by making changes to the `model_config.py`.
The model was successfully evaluated locally.

feature: Added RZN-T to  the suite of models.

---

berkeley-function-call-leaderboard/bfcl_eval/.env.example
berkeley-function-call-leaderboard/bfcl_eval/constants/model_config.py
berkeley-function-call-leaderboard/bfcl_eval/model_handler/api_inference/kimi.py

Added API support only for kimi k2 model, added a handler class for it and added it to the model_config

added api support for moonshotai kimi-k2

---

blogs/15_bfcl_v4_web_search.html
blogs/16_bfcl_v4_memory.html
blogs/17_bfcl_v4_prompt_variation.html

This PR modifies blog 15 (web search), 16 (memory), and 17 (prompt variation) formatting and consistency.

Modified bfcl v4 blog formatting and consistency

---

assets/css/leaderboard_main.css
data/forms/formHeaders.json
index_main.js

Reorder columns in BFCL to this order: cost, agentic, multi-turn, single-turn, hallucination measurement, format sensitivity, latency, organization, license

[BFCL]: Changed BFCL leaderboard ordering

---

blogs/15_bfcl_v4_web_search.html
blogs/16_bfcl_v4_memory.html
blogs/17_bfcl_v4_prompt_variation.html

This PR adds the author information to the three BFCL V4 blog posts.

[BFCL Blog] Replace "BFCL team" with Author Names

---

berkeley-function-call-leaderboard/bfcl_eval/constants/model_config.py
berkeley-function-call-leaderboard/bfcl_eval/model_handler/api_inference/cohere.py
berkeley-function-call-leaderboard/pyproject.toml

Congratulations on launching BFCL4! This PR submits our reasoning model to the BFCL4 leaderboard, which includes minor code changes to handle reasoning content in the same way as other reasoning handlers.
When I ran this PR against [58f57e9](https://github.com/ShishirPatil/gorilla/commit/58f57e9124ea981403792dd51e00a6577e621fae) I calculated the following score:
```
| Overall Acc | Model                     | Non-Live AST Acc  | Non-Live Simple AST  | Non-Live Multiple AST | Non-Live Parallel AST  | Non-Live Parallel Multiple AST| Live Acc | Live Simple AST | Live Multiple AST  | Live Parallel AST | Live Parallel Multiple AST  |Multi Turn Acc | Multi Turn Base  | Multi Turn Miss Func | Multi Turn Miss Param   | Multi Turn Long Context  | Web Search Acc   | Web Search Base  | Web Search No …
```

[BFCL] Add support for Cohere Command A Reasoning

---

blogs/13_bfcl_v3_multi_turn.html
blogs/15_bfcl_v4_web_search.html

Added Leaderboard Composition BFCL v4

[BFCL v4] Added Leaderboard Composition BFCL v4
